Repository smutel/go-netbox, pull requests merged in 2022-09, with the labels that each got.

#39 feat: Add go.mod and build improvements
  go.mod
  go.sum
  utils/netbox_generate_client
Labels: enhancement

#41 feat: Allow Create functions for available prefix/ip to be used
  .gitignore
  patchs/swagger-v3.2.9-available-ip.patch
Labels: enhancement

#42 feat: Add patch to remove primary IP
  patchs/swagger-v3.2.9-primary-ip.patch
Labels: enhancement

#43 chore(release): 3.2.1
  CHANGELOG.md
  package.json
Labels: chore

#46 chore(release): 3.2.2
  CHANGELOG.md
  package.json
Labels: chore

#47 ci: Update go-swagger to v0.30.2
  utils/netbox_generate_client
Labels: ci
